### ISSUE TITLE
How to use this.$http.post syncronously, not async?

### ISSUE THREAD

**Issue by Danjavia** [vuejs/vue-resource#179]

**Comment by jorgemurta** [comment]
+1

**Comment by jnggao** [comment]
+1

**Comment by genhoi** [comment]
+1

**Comment by steffans** [comment]
Syncronous request have negative effects to the user experience, because the browser becomes unresponsive. Normally you can accomplish everything using the asynchronous request and the returned promises.

**Comment by kirkbushell** [comment]
just return the promise, and work with success/fails in your business domain.

**Comment by amirrustam** [comment]
There is really no point to a synchronous request since you can't get around waiting for a response. As @steffans and @kirkbushell said, work withe promises to get the desired effect. 

@Danjavia I think this issue can be closed out, unless you have something else to add.

**Comment by Danjavia** [comment]
Thanks guys. But you cannot understand me :)

**Comment by smolinari** [comment]
Then explain yourself better or at least try. 

Scott

**Comment by Danjavia** [comment]
Thx again guys, the issue was solved using other method :)

**Comment by one-shy** [comment]
@Danjavia So what the method to solved this issue.

@steffans This exactly is a trouble in my project. Use _promise_ is not a easy way to deal with multi requests. So I want to package the requests but without sync method.

**Comment by one-shy** [comment]
@Danjavia So what the method to solved this issue.

@steffans This exactly is a trouble in my project. Use promise is not a easy way to deal with multi requests. So I want to package the requests but without sync method.

**Comment by Yiin-** [comment]
I'd like to open another tab with payment url after reservation is created successfully, and appearently it's not possible without sending request syncronously, because window.open(url, '_blank'); needs to be called on actual click event.

**Comment by audiolion** [comment]
there is good reason for that, if any arbitrary javascript could open a new tab on the user's web browser and put in any url, imagine how abusive that could be.

What you can do here is use a small single-page-application interface where the returned promise redirects to a new router url which calls and renders a new component on the page, e.g. your payment success, in the interim you can show a modal with a spinner.

Rather than try to do something that creates an awful user experience, (synchronous requests), I would redesign your approach to solving the problem of navigating to the reservation screen.

**Comment by IvanovPvl** [comment]
+1
Chrome block window.open(url, '_blank')

**Comment by Yiin-** [comment]
oh, @audiolion, I know why chrome does that and fully agree to that, but in my use case I'd like to use synchronous request without searching for workarounds who actually create awful user experience in this case (because now user needs to click twice).

**Comment by hermandinho** [comment]
+1

**Comment by DomenicRoti** [comment]
+1

**Comment by wuwenjie** [comment]
+1

**Comment by michaelcouck** [comment]
+1

I need the data loaded before the page loads or the population of the elements do not get styled correctly. 

The argument that it interferes with UX has no grounds, if the page loads before the data there is nothing for the user to see anyway, ergo, load the data first. And indeed if the data load fails, then once again there is nothing for the user to see. The data load and page render are a single atomic unit of work.

Hence, please add a synchronous get/post call, and I will be a very happy camper ;)

**Comment by adolphlwq** [comment]
+1

**Comment by mrzorn** [comment]
+1 exactly for the reasons that @michaelcouck specified.

**Comment by lengyuedaidai** [comment]
+1

**Comment by zeidanbm** [comment]
+1

**Comment by kravemir** [comment]
+1

**Comment by billzee** [comment]
+1

**Comment by andreixk** [comment]
+1

**Comment by fenixrw** [comment]
@michaelcouck I think the issue you pointed out can be solved another way. You can 

`
<div id="app">
  <div v-if="loaded">
    <p>{{ message }}</p>
    
  </div>
  <div v-else>
    <p>Loading</p>
    
  </div>
</div>
`

`
new Vue({
  el: '#app',
  data: {
  	loaded: false,
    message: 'Hello Vue.js!'
  },
  methods:
  {
  	loadPage: {
      // POST /someUrl
      this.$http.post('/someUrl', {foo: 'bar'}).then(response => {
        //success callback
        this.loaded = true;
      }, response => {
        // error callback
      });
    }	
  }
})
`

**Comment by octave** [comment]
+1 Shopify JavaScript API requires to queue up Ajax requests synchronously: https://help.shopify.com/themes/development/getting-started/using-ajax-api#add-to-cart

**Comment by clockworked247** [comment]
I'm going to pile on here with another +1 with what I believe is a valid use case for synchronous.

I have a formerly jQuery single page app that I'm porting to Vue web app that saves state to the server when the browser is closed using 'beforeunload'.  When using jQuery you could set the synchronous flag on an $.ajax request making a blocking call that would complete before the page unloaded.   

Since I'm now using vue-resource to handle this same request on 'beforeunload', which is now asynchronous, the request to the server will be terminated by the client without completing the save to the server. 

So right now, without a synchronous flag, I will need to write my own vanilla JS ajax request method just for this use case, which is not ideal.

**Comment by shozayen** [comment]
+1

**Comment by truefusion** [comment]
For modern browsers that support **await**, the following should work since it returns a promise:
`var rsp = await this.$http.post('/some-url', {some: 'data'});`
