### ISSUE TITLE
has a bug under IE10

### ISSUE THREAD

**Issue by del1214** [vuejs/vue-resource#372]
vue resource will add an 'undefined' string before url under IE10

**Comment by LinusBorg** [comment]
Please provide a reproduction example.

**Comment by blake-newman** [comment]
Please follow the [Vue.js issue template](https://github.com/vuejs/vue/edit/dev/issue_template.md). 

Briefly an issue should contain:
- Dependency versions
- Steps necessary to reproduce the issue you are running into.
- A JSFiddle/JSBin/Codepen to demonstrate your issue. You could start with [this template](http://jsfiddle.net/5sH6A/) that already includes the latest version of Vue.

If no information is provided, this issue will be closed within 5 days. If the issue is closed please reopen when relevant information is provided.

Thanks.
