### ISSUE TITLE
Support for Http2?

### ISSUE THREAD

**Issue by thanosalexander** [vuejs/vue-resource#382]
Does it have support fot http2?
Currently the only way to get content from response is to parse manually response.data to Json

**Comment by avitex** [comment]
When you say support, is there a specific feature you have in mind?
This library uses [XMLHttpRequest](https://developer.mozilla.org/en-US/docs/Web/API/XMLHttpRequest) by [default](https://github.com/vuejs/vue-resource/blob/master/src/http/client/index.js#L68), which is just a higher level wrapper around the internal HTTP client in the browser. The real question is if the server and the browser support HTTP/2. Personally, I wouldn't worry about this on the client side, [most major browsers do](http://caniuse.com/#feat=http2), and you don't need to have any control over this, or at least today.

As for the response, this library is promise based, and even content parsing/retrieval is promise based (I assume due to making this future proof for upcoming browser API's like [fetch](https://developer.mozilla.org/en/docs/Web/API/Fetch_API), or just following best practices). To get the json, you'll want to call the [`json` function on the response](https://github.com/vuejs/vue-resource/blob/master/src/http/response.js#L42), which will return a promise for your parsed data.

```js
this.$http.get('/api/cats/nyan').then((response) => {
  // This is the success callback
  // We can call `json()` to get the promise and
  // `then` do something 
  response.json().then((data) => {
    // Use parsed JSON
    console.log(data)
  }, (error) =>  { 
    // JSON parsing failed
  }
}, (response) => {
  // Failed to make request
})
```
But we could make this DRYer by chaining the promise

```js
this.$http.get('/api/cats/nyan')
// Arrow functions can return something implicitly,
// so we can return another promise, this time to
// the data (chaining)
.then((response) => response.json()) 
.then((data) => {
   // Use parsed JSON
    console.log(data)
}, (error) => {
  // Failed to make request, or JSON parsing failed
})
```
