### ISSUE TITLE
response.body , sometimes get a json Object, sometimes get a json string

### ISSUE THREAD

**Issue by vopjie** [vuejs/vue-resource#443]
help

**Comment by craigpaul** [comment]
@vopjie In order to help you we need more information. What version of vue-resource are you using? This sounds like a bug that got squashed in ~1.0, so I'm guessing you're on ~0.9? If so, please upgrade and verify if you're still having this problem. I believe it was #317, but I could be wrong about that.

**Comment by vopjie** [comment]
@craigpaul oh yes, it helped, thanks!
when i run my project in dev environment, the response header does't have 'Content-Type:application/json', then the response.body get a json string.
and i want to know if it's right code like this:
![image](https://cloud.githubusercontent.com/assets/9351855/19190078/fb5901bc-8ccd-11e6-918b-fcd84a04c21c.png)

**Comment by craigpaul** [comment]
@vopjie yup that code looks correct to me. If you are wanting to stay on your current version of vue resource, I suggest you put that in an interceptor as described in that previous issue, otherwise you'd be rewriting that in every promise.

**Comment by vopjie** [comment]
@craigpaul i just get confused. when the response header does't have 'Content-Type:application/json', then the response.body need to be transformed json object ( JSON.parse() ), is that right?
here is the code in vue-resource@1.0.3, but the result just on the contrary
![image](https://cloud.githubusercontent.com/assets/9351855/19197315/bb0920a6-8ceb-11e6-8832-63ed9220ed96.png)

**Comment by craigpaul** [comment]
Sorry, read your code a bit too fast. You did have them backwards. If the `type.indexOf()` call passes then you are assumed to be receiving json, i must have saw a `-1` when I read yours quickly for some reason. Sorry about that. Did upgrading to `1.0.3` fix your problem though?

**Comment by vopjie** [comment]
@craigpaul oh, i got it. it means i must have 'Content-Type:application/json' in the response header, then vue-resource will do the transformation.

if it's could be possible that i white 'dataType: json' in the request options,  then the server will know what i need and return a json object, just like the $.ajax ?
![image](https://cloud.githubusercontent.com/assets/9351855/19210269/c7689664-8d50-11e6-895d-cfd84aa25daf.png)

sorry for my poor English.

**Comment by craigpaul** [comment]
Yes, assuming your on 1.0 or greater, having that as your content type will make vue-resource parse your response as JSON as you showed above. 

As for dataType in jQuery, it doesn't actually do anything when sending the request, it is used to explicitly tell jQuery how you want the response parsed. It is essentially a trigger to run JSON.parse() on the response (or a different implementation in older browsers). So in short, no there is no dataType option in vue-resource, but that is because you don't need it. As long your server returns the proper Content-Type header, you'll be fine.

**Comment by vopjie** [comment]
@craigpaul thanks a lot!
