### ISSUE TITLE
Interceptor not fired from created hook on full page reload

### ISSUE THREAD

**Issue by rightaway** [vuejs/vue-resource#457]
In this standalone project https://github.com/rightaway/demo you'll see that the I use a `created` hook to make an HTTP request using `this.$http.get` (https://github.com/rightaway/demo/blob/master/src/Home.vue#L11).

However, the interceptor https://github.com/rightaway/demo/blob/master/src/index.js#L16 doesn't get fired when I load the page from a browser reload. But if I click to another link on that page (e.g. `Login`) and then click back to the main link `Home`, the interceptor does get fired and the console.log occurs.

Why does the interceptor not fire on initial page load?

**Comment by pzanitti** [comment]
That's because the interceptor is added after Home component's created() hook runs.

You can either place the interceptor before `const vm = new Vue({` or mount the vm after the interceptor:
```
const vm = new Vue({
  router,
  store,
})

Vue.http.interceptors.push((request, next) => {
  console.log('before-request')
  next()
});

vm.$mount('#app');
```

**Comment by rightaway** [comment]
That solves it for the created() hook, thanks! I've pushed a new commit to the repository https://github.com/rightaway/demo that demonstrates the same problem but for `beforeRouteEnter`. When you do a full page reload of the main page, the console.log output is

```
beforeRouteEnter
created
before-request
```

But if you navigate back to the page using links, you get 
```
beforeRouteEnter
before-request
created
before-request
```

Which means that the interceptors aren't getting fired on a full page reload when the request comes from `beforeRouteEnter`. (Not sure if it's relevant but in `beforeRouteEnter` I use `Vue.http` because `this.$http` isn't available yet, as it is in the created() hook.)

**Comment by pzanitti** [comment]
Now what is happening is that when you instantiate the VM, you're calling the router set up. It loads Home by default and so beforeRouteEnter is called.

What you actually do with $mount is place the VM in the document, but the part of the lifecycle that executes its router transition has already been called.

Let's switch it up again:

```
Vue.http.interceptors.push((request, next) => {
  console.log('before-request')
  next()
});

const vm = new Vue({
  router,
  store,
});

vm.$mount('#app');
```

Now we have

```
[HMR] Waiting for update signal from WDS...
Home.vue:18 beforeRouteEnter // Starting on Home
index.js:11 before-request
Home.vue:13 created
index.js:11 before-request
client?cbff:37 [WDS] Hot Module Replacement enabled.
Home.vue:18 beforeRouteEnter // Going to Login and coming back Home
index.js:11 before-request
Home.vue:13 created
index.js:11 before-request
```

**Comment by rightaway** [comment]
That does work! Thank you for your help.

I notice you use the term "in-document". I've also seen that term elsewhere like http://vuejs.org/guide/migration.html#ready-deprecated. What does that mean and what is the implication of whether something happens in-document vs otherwise?

**Comment by pzanitti** [comment]
If you look at the Lifecycle Diagram, you will see that many things happen before a template can be drawn to screen (mounted), and there's also a mention of a virtual DOM, that is, the document object model that is stored in memory but not yet drawn to screen. I'm being very crude with the language so you can understand the concepts, but don't quote me on this.

![Vue.js Lifecycle Diagram](https://vuejs.org/images/lifecycle.png)

If we had a `<input id="someInput" v-model="someData">` field where 'someData' is originally the string 'Hello' and on our code we did something like:
```
this.someData = 'World'
console.log(document.getElementById('someInput').value)
```
Surprisingly the console would log `Hello` and not `World`, because the virtual DOM hasn't yet replaced the real DOM.

This is where `Vue.nextTick` comes handy, as it waits for the next DOM update to run its callback. You are going to use it a lot if you use plugins like jQuery which work on the real DOM and not on Vue's virtual DOM.

You can see an example here https://jsfiddle.net/5sH6A/794/. The first `console.log()` is not what we wanted, the second is. I don't say it's wrong because it's technically not wrong, it's how it's supposed to behave.

I know this might sound too contrived, but these are edge cases and you'll be learning them step by step.

**Comment by rightaway** [comment]
I've read it over a few times and it's more clear now, thank you so much.

**Comment by PeterSeng** [comment]
@pzanitti Thanks.Your answer help me also.
